apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
# these are deployment labels
  labels:
    purpose: headless-svc-demo
    project: safety
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: headless-svc-demo
      project: safety
    # pod definition
  template: 
    metadata:
      labels:
        purpose: headless-svc-demo
        project: safety
    spec:
      containers:
      - name: nginx
        image: nginx