apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
# these are deployment labels
  labels:
    purpose: taint-demo   
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: taint-demo
    # pod definition
  template: 
    metadata:
      labels:
        purpose: taint-demo   
    spec:
      containers:
      - name: nginx
        image: nginx